### ISSUE TITLE
How to work wifi

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/ThinkPad-E560-Hackintosh#20]
Hello.  
I installed McCatalina on my Lenovo E560 laptop.Of course with your tips.  
Is it possible to use WiFi ?!  Because it does not seem to work.  And the second question is how to install Mac Big Sur on my laptop and it works like the current Mac ?! 🌹🙏🏻

**Comment by rsdev69** [comment]
> Hello.
> I installed McCatalina on my Lenovo E560 laptop.Of course with your tips.
> Is it possible to use WiFi ?! Because it does not seem to work. And the second question is how to install Mac Big Sur on my laptop and it works like the current Mac ?! 🌹🙏🏻

This is my last EFI with working native Intel WiFi and Big Sur Beta
https://mega.nz/file/2kFgQJob#LQmxb7tndnybHWV2ojkNrK3pjM61PxU88HMNXJ5-7ro
