### ISSUE TITLE
Efi for catalina

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/ThinkPad-E560-Hackintosh#21]
Hello.  
I received your Catalina efi file.  But its content is completely different from my efi file!  I installed Canalina and Windows 10 on my laptop.  
my efi file is like the image below.  
Is there a problem with my Windows 10 by replacing your file?  
please guide me.

![image](https://user-images.githubusercontent.com/11042152/97079298-9d031200-15ff-11eb-8c2b-992e5f2d23a1.jpeg)

**Comment by rsdev69** [comment]
> Hello.
> I received your Catalina efi file. But its content is completely different from my efi file! I installed Canalina and Windows 10 on my laptop.
> my efi file is like the image below.
> Is there a problem with my Windows 10 by replacing your file?
> please guide me.

Hello.
I do not understand what the problem is. 
Use the latest files from repo. 
Replace the one you need EFI folder.
![1](https://user-images.githubusercontent.com/34169770/97082618-b0b87380-1613-11eb-99b0-619e8bc5bf0d.png)

**Comment by javadmahmoodi** [comment]
I asked you to give me the efi that supports WiFi and you gave me the catalina version.  
But the content of the efi folder you gave me is different from the content of my efi folder in terms of category.  
Doesn't that cause a problem?  And will the problem be implemented?

**Comment by rsdev69** [comment]
> I asked you to give me the efi that supports WiFi and you gave me the catalina version.
> But the content of the efi folder you gave me is different from the content of my efi folder in terms of category.
> Doesn't that cause a problem? And will the problem be implemented?

Download the latest files from the repository, all the latest changes are there.
![2](https://user-images.githubusercontent.com/34169770/97086326-2845cd00-162b-11eb-9604-2ee3431b7464.png)

**Comment by javadmahmoodi** [comment]
What should I replace between my efi folder between efi clover and efi mac os catalina?

**Comment by rsdev69** [comment]
> What should I replace between my efi folder between efi clover and efi mac os catalina?

Just mount your EFI partition, delete all files and insert BOOT and OC folder.
![2](https://user-images.githubusercontent.com/34169770/97088763-c2ae0c80-163b-11eb-9049-550df36696b2.png)

**Comment by javadmahmoodi** [comment]
Hello.  
I replaced the new folder.  Everything is fine, but the Apple logo is very big when the Mac comes up.  
Is there a way to adjust the size of the logo when the Mac comes up?

![image](https://user-images.githubusercontent.com/11042152/97099738-a5ac2480-16a1-11eb-97c4-21fe9461f913.jpeg)

**Comment by rsdev69** [comment]
> Hello.
> I replaced the new folder. Everything is fine, but the Apple logo is very big when the Mac comes up.
> Is there a way to adjust the size of the logo when the Mac comes up?

1.Replase config.plist
[Config.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5434366/Config.zip)
2. Reset NVRAM!!!
![image](https://user-images.githubusercontent.com/34169770/97103547-cbdbbf80-16b5-11eb-90fc-e6677028c96d.png)

**Comment by javadmahmoodi** [comment]
I did.  
Logo and item sizes were adjusted.  But under the Apple logo, the line that should be filled in is not shown !!  Fire extinguishing help

![image](https://user-images.githubusercontent.com/11042152/97103757-bd94a000-16c3-11eb-9d92-2735c97857f8.jpeg)

**Comment by rsdev69** [comment]
> I did.
> Logo and item sizes were adjusted. But under the Apple logo, the line that should be filled in is not shown !! Fire extinguishing help

Forse  shutdown pc and reset NVRAM again.

**Comment by javadmahmoodi** [comment]
I turned the system off and on and hit the option you mentioned.  The system was reset.  But still the line below the Apple logo is not shown

**Comment by javadmahmoodi** [comment]
> > I did.
> 
> > Logo and item sizes were adjusted. But under the Apple logo, the line that should be filled in is not shown !! Fire extinguishing help
> 
> 
> 
> Forse  shutdown pc and reset NVRAM again.

I realized something.  
Before showing the boot, this post is displayed in the upper left corner.

![image](https://user-images.githubusercontent.com/11042152/97103992-61328000-16c5-11eb-984a-db872899d27e.jpeg)

**Comment by rsdev69** [comment]
> > > I did.
> > 
> > 
> > > Logo and item sizes were adjusted. But under the Apple logo, the line that should be filled in is not shown !! Fire extinguishing help
> > 
> > 
> > Forse  shutdown pc and reset NVRAM again.
> 
> I realized something.
> Before showing the boot, this post is displayed in the upper left corner.
> 
> ![image](https://user-images.githubusercontent.com/11042152/97104018-9f2fa400-16c5-11eb-9ed9-b06d91378e0a.jpeg)

Try this config
[Config.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5434449/Config.zip)

**Comment by javadmahmoodi** [comment]
> > > > I did.
> 
> > > 
> 
> > > 
> 
> > > > Logo and item sizes were adjusted. But under the Apple logo, the line that should be filled in is not shown !! Fire extinguishing help
> 
> > > 
> 
> > > 
> 
> > > Forse  shutdown pc and reset NVRAM again.
> 
> > 
> 
> > I realized something.
> 
> > Before showing the boot, this post is displayed in the upper left corner.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/11042152/97104018-9f2fa400-16c5-11eb-9ed9-b06d91378e0a.jpeg)
> 
> 
> 
> Try this config
> 
> [Config.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5434449/Config.zip)
> 
> 

How do I replace this file now?  The Mac does not pop up and the logo is only displayed

**Comment by rsdev69** [comment]
> How do I replace this file now? The Mac does not pop up and the logo is only displayed

Make USB with EFI and boot from USB 
Replase EFI

**Comment by javadmahmoodi** [comment]
> > > > I did.
> 
> > > 
> 
> > > 
> 
> > > > Logo and item sizes were adjusted. But under the Apple logo, the line that should be filled in is not shown !! Fire extinguishing help
> 
> > > 
> 
> > > 
> 
> > > Forse  shutdown pc and reset NVRAM again.
> 
> > 
> 
> > I realized something.
> 
> > Before showing the boot, this post is displayed in the upper left corner.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/11042152/97104018-9f2fa400-16c5-11eb-9ed9-b06d91378e0a.jpeg)
> 
> 
> 
> Try this config
> 
> [Config.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5434449/Config.zip)
> 
> 

I replaced your config file through Dual Boot and Windows 10, but the problem was not resolved.

**Comment by rsdev69** [comment]
> I replaced your config file through Dual Boot and Windows 10, but the problem was not resolved.

Replase full EFI folder
https://mega.nz/file/HoFXRCoR#w4QZcLvoj0-Ol-ZxEds5TchwMy2ScDVSWrftUvdwjiw

**Comment by javadmahmoodi** [comment]
> > I replaced your config file through Dual Boot and Windows 10, but the problem was not resolved.
> 
> 
> 
> Replase full EFI folder
> 
> https://mega.nz/file/HoFXRCoR#w4QZcLvoj0-Ol-ZxEds5TchwMy2ScDVSWrftUvdwjiw

Thank.  problem solved.  Just what I do after entering my Apple ID and password shows the following message.  This is while before replacing my Apple ID efi file, it worked and had no problems.  Can you help?

**Comment by rsdev69** [comment]
> Thank. problem solved. Just what I do after entering my Apple ID and password shows the following message. This is while before replacing my Apple ID efi file, it worked and had no problems. Can you help?

You need to generate your persomal SMBIOS 
https://github.com/corpnewt/GenSMBIOS

**Comment by rsdev69** [comment]
> Thank. problem solved. Just what I do after entering my Apple ID and password shows the following message. This is while before replacing my Apple ID efi file, it worked and had no problems. Can you help?

I found errors in files in the repository. I have updated all files to the most recent. Download the latest update, all bugs are fixed.
![2](https://user-images.githubusercontent.com/34169770/97115099-5abffa80-16fd-11eb-8073-8348884f1de2.png)

**Comment by rsdev69** [comment]
> Thank. problem solved. Just what I do after entering my Apple ID and password shows the following message. This is while before replacing my Apple ID efi file, it worked and had no problems. Can you help?

I created a specially completely updated bootloader for you with all Apple services.
Just replase full EFI folder
https://mega.nz/file/L8El0ITR#ZwflgoshBHy6_C-u2Pd_qk54WWC3Hmy_mI7idcmTbz4
