### ISSUE TITLE
Works 100% but not Wi-Fi

### ISSUE THREAD

**Issue by gabrielecapp** [rsdev69/ThinkPad-E560-Hackintosh#22]
Hi! I have the i5-6200u one. It works very well but I had an issue. WiFi worked for half an hour but not won't connect to networks. How can I do?
Thanks!

**Comment by rsdev69** [comment]
> Hi! I have the i5-6200u one. It works very well but I had an issue. WiFi worked for half an hour but not won't connect to networks. How can I do?
> Thanks!

Wifi work not stable, it's true. Kext for intel still in development and no stable now. For me on Catalina wifi work well, when the connection is lost i reset NVARAM and wifi work. On last Catalina wifi not work. If you really need wifi use HeliPort. This is most stable solution.  
https://github.com/OpenIntelWireless/HeliPort

**Comment by gabrielecapp** [comment]
do it works 100% with heliport? 
ps: I have a Broadcom BCM94352Z, if I install it in the E560? 🤔

**Comment by rsdev69** [comment]
> do it works 100% with heliport?
> ps: I have a Broadcom BCM94352Z, if I install it in the E560? 🤔

Heliport work normal with intel wifi. BCM94352Z work 100% in macOS. You need install kext and patch for BCM94352Z and cart will be native detect in macOS. I don't intall any other cart because in my bios need delete Whitelist for other wifi cart.
