### ISSUE TITLE
Do not run Mac Big Sur after installation

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/ThinkPad-E560-Hackintosh#23]
Hello.  I built and installed the MacBig Sur boot.  But when the Apple logo comes in and the bottom line starts to fill up, the system restarts at the end of the line and the Mac Big Sur does not go up.  please guide me

![image](https://user-images.githubusercontent.com/11042152/99142280-bcbeb080-2668-11eb-8c37-77bd369c6b7c.jpeg)

![image](https://user-images.githubusercontent.com/11042152/99142306-11fac200-2669-11eb-812a-bc3ee89d722b.jpeg)

**Comment by rsdev69** [comment]
> Hello. I built and installed the MacBig Sur boot. But when the Apple logo comes in and the bottom line starts to fill up, the system restarts at the end of the line and the Mac Big Sur does not go up. please guide me

macOS Big Sur release not support in this moment. Now i need test and make new config for Big Sur. Update from Catalina to Big Sur not possible only clean installation!

**Comment by javadmahmoodi** [comment]
> > Hello. I built and installed the MacBig Sur boot. But when the Apple logo comes in and the bottom line starts to fill up, the system restarts at the end of the line and the Mac Big Sur does not go up. please guide me
> 
> 
> 
> macOS Big Sur release not support in this moment. Now i need test and make new config for Big Sur. Update from Catalina to Big Sur not possible only clean installation!
> 
> 

I mean, should I install and use Catalina?

**Comment by rsdev69** [comment]
> I mean, should I install and use Catalina?

Catalina work stable and no issue.

**Comment by javadmahmoodi** [comment]
> > I mean, should I install and use Catalina?
> 
> 
> 
> Catalina work stable and no issue.

Can you tell me when to get the EFI file for the Big Sur release version?

**Comment by rsdev69** [comment]
> Can you tell me when to get the EFI file for the Big Sur release version?

I think update will be ready today)

**Comment by javadmahmoodi** [comment]
> > Can you tell me when to get the EFI file for the Big Sur release version?
> 
> 
> 
> I think update will be ready today)

So I am waiting for your update.
I am not currently installing Catalina.  
Please let me know so I can quickly install Big Sur today.  
Thankful.  
My email: jmahmoodi5967@gmail.com and 
my telegram ID: javadmahmoodi

**Comment by rsdev69** [comment]
> > > Can you tell me when to get the EFI file for the Big Sur release version?
> > 
> > 
> > I think update will be ready today)
> 
> So I am waiting for your update.
> I am not currently installing Catalina.
> Please let me know so I can quickly install Big Sur today.
> Thankful.
> My email: [jmahmoodi5967@gmail.com](mailto:jmahmoodi5967@gmail.com) and
> my telegram ID: javadmahmoodi

Big Sur ready! All work! All update!
<img width="576" alt="Screenshot 2020-11-14 at 15 08 13" src="https://user-images.githubusercontent.com/34169770/99147675-8181a900-268b-11eb-981f-ed27d3420da9.png">
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5540746/EFI.zip)

**Comment by javadmahmoodi** [comment]
> > > > Can you tell me when to get the EFI file for the Big Sur release version?
> 
> > > 
> 
> > > 
> 
> > > I think update will be ready today)
> 
> > 
> 
> > So I am waiting for your update.
> 
> > I am not currently installing Catalina.
> 
> > Please let me know so I can quickly install Big Sur today.
> 
> > Thankful.
> 
> > My email: [jmahmoodi5967@gmail.com](mailto:jmahmoodi5967@gmail.com) and
> 
> > my telegram ID: javadmahmoodi
> 
> 
> 
> Big Sur ready! All work! All update!
> 
> <img width="576" alt="Screenshot 2020-11-14 at 15 08 13" src="https://user-images.githubusercontent.com/34169770/99147675-8181a900-268b-11eb-981f-ed27d3420da9.png">
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5540746/EFI.zip)
> 
> 

Thankful.  
Does it work with this WiFi EFI?

**Comment by rsdev69** [comment]
> Does it work with this WiFi EFI?

Yes!
All work!

**Comment by javadmahmoodi** [comment]
> > Does it work with this WiFi EFI?
> 
> 
> 
> Yes!
> 
> All work!
> 
> 

very good.  Let me try and let you know the result here.

**Comment by javadmahmoodi** [comment]
> > Does it work with this WiFi EFI?
> 
> 
> 
> Yes!
> 
> All work!
> 
> 

I started installing.  
But so far I have encountered two problems.  
First, in the installation of Big Sur, the touchpad does not work and I have to use the mouse.  Secondly, the Apple logo and drives are very large. Thank you for telling me how to fix these two problems.

![image](https://user-images.githubusercontent.com/11042152/99148724-b1867780-269e-11eb-8c3c-a19ce9c48773.jpeg)

**Comment by rsdev69** [comment]
> First, in the installation of Big Sur, the touchpad does not work and I have to use the mouse. Secondly, the Apple logo and drives are very large. Thank you for telling me how to fix these two problems.

Reset NVRAM and replace this EFI
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5540859/EFI.zip)

**Comment by javadmahmoodi** [comment]
> > First, in the installation of Big Sur, the touchpad does not work and I have to use the mouse. Secondly, the Apple logo and drives are very large. Thank you for telling me how to fix these two problems.
> 
> 
> 
> Reset NVRAM and replace this EFI
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5540859/EFI.zip)
> 
> 

Everything works very well. 
But when Mac wants to come up, instead of the Apple logo and the line below, long text is displayed.  Like the photo below.  
Is it possible to see something clean and bogo and the line below it instead of these writings which do not look interesting at all?

![image](https://user-images.githubusercontent.com/11042152/99152280-139ea700-26b6-11eb-8413-c5b5ba7c6318.jpeg)

**Comment by rsdev69** [comment]
> > > First, in the installation of Big Sur, the touchpad does not work and I have to use the mouse. Secondly, the Apple logo and drives are very large. Thank you for telling me how to fix these two problems.
> > 
> > 
> > Reset NVRAM and replace this EFI
> > [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5540859/EFI.zip)
> 
> Everything works very well.
> But when Mac wants to come up, instead of the Apple logo and the line below, long text is displayed. Like the photo below.
> Is it possible to see something clean and bogo and the line below it instead of these writings which do not look interesting at all?

Replace and Reset NVRAM
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5541226/EFI.zip)

**Comment by javadmahmoodi** [comment]
Everything was fine.  After restarting, unfortunately, I came across the image below.  What is the reason for this and what is the solution?

![image](https://user-images.githubusercontent.com/11042152/99158317-a5260d00-26e6-11eb-9da3-e129edcedf42.jpeg)
