### ISSUE TITLE
Disable Bluetooth mouse

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/ThinkPad-E560-Hackintosh#24]
Hi. I found out after installing Big Sur that my Apple ID does not work with Big Sur. After inserting the uuid and serial number, my Apple ID worked but my Bluetooth mouse failed. Please help me. 
The EFI file is attached

[https://mega.nz/file/7LhigKwa#MxFsZcy7R32k5lNfbAoggwTGZyt8eV4XOT12525MCcE](url)

**Comment by rsdev69** [comment]
> Hi. I found out after installing Big Sur that my Apple ID does not work with Big Sur. After inserting the uuid and serial number, my Apple ID worked but my Bluetooth mouse failed. Please help me.

Bluetooth not working in Big Sur. No working kext for IntelBluetoothFirmware. No solution now.

**Comment by javadmahmoodi** [comment]
My mouse is a simple mouse that worked with Big Bluetooth in Big Sur. After inserting uuid to apply Apple ID, it did not work all at once.

**Comment by javadmahmoodi** [comment]
> > Hi. I found out after installing Big Sur that my Apple ID does not work with Big Sur. After inserting the uuid and serial number, my Apple ID worked but my Bluetooth mouse failed. Please help me.
> 
> Bluetooth not working in Big Sur. No working kext for IntelBluetoothFirmware. No solution now.

Now I understand something. None of the USB ports work. This happened after setting uuid to apply Apple ID. please help

**Comment by rsdev69** [comment]
> Now I understand something. None of the USB ports work. This happened after setting uuid to apply Apple ID.
> Can you look at the EFI file I sent you the link to? I may have made a mistake somewhere I did not realize.
> please help

You generate wrong SMBIOS!
I make new SMBIOS for you.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5542032/EFI.zip)

**Comment by javadmahmoodi** [comment]
>  > Now I understand something. None of the USB ports work. This happened after setting uuid to apply Apple ID.
> 
> > Can you look at the EFI file I sent you the link to? I may have made a mistake somewhere I did not realize.
> 
> > please help
> 
> 
> 
> You generate wrong SMBIOS!
> 
> I make new SMBIOS for you.
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5542032/EFI.zip)
> 
> 

Thanks a lot.  Only now have the Apple logo and hard drives become so big and ugly again.  How do I reduce the size of the Apple logo and hard drives?

**Comment by rsdev69** [comment]
> Thanks a lot. Only now have the Apple logo and hard drives become so big and ugly again. How do I reduce the size of the Apple logo and hard drives?

Replace EFI and reset NVRAM
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5542067/EFI.zip)

**Comment by javadmahmoodi** [comment]
> > Thanks a lot. Only now have the Apple logo and hard drives become so big and ugly again. How do I reduce the size of the Apple logo and hard drives?
> 
> 
> 
> Replace EFI and reset NVRAM
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/5542067/EFI.zip)
> 
> 

Thank you very much.  How do I set up SMBIOS correctly to do this for myself next time?

**Comment by rsdev69** [comment]
> How do I set up SMBIOS correctly to do this for myself next time?

Simple download app OpenCore Configurator
https://mackie100projects.altervista.org/opencore-configurator/
Open your config.plist
<img width="1265" alt="Screenshot 2020-11-15 at 17 24 09" src="https://user-images.githubusercontent.com/34169770/99188982-9f244080-2767-11eb-8f0d-55b8453d3c9d.png">
<img width="746" alt="Screenshot 2020-11-15 at 17 25 03" src="https://user-images.githubusercontent.com/34169770/99188985-a2b7c780-2767-11eb-8069-22a6cf4a1b33.png">
Save config.
