### ISSUE TITLE
Question about Catalina

### ISSUE THREAD

**Issue by rajolm** [rsdev69/ThinkPad-E560-Hackintosh#25]
Hi,
Thanks for your hard work on this project
I have a few questions
Can I use you last commit (Nov 25, 2020) with macOS Catalina? or I should use the earlier version from Nov 17, 2020?
also how I can do dual boot with Windows?
Currently I'm using Clover and Add Windows partition to Config.plist, how I can get windows partition work with clover?

Many thanks!

**Comment by rsdev69** [comment]
> Hi,
> Thanks for your hard work on this project
> I have a few questions
> Can I use you last commit (Nov 25, 2020) with macOS Catalina? or I should use the earlier version from Nov 17, 2020?
> also how I can do dual boot with Windows?
> Currently I'm using Clover and Add Windows partition to Config.plist, how I can get windows partition work with clover?
> 
> Many thanks!

Hi, 
Use latest commit from repo with OpenCore. Now no need other version for Mojave, Catalina or BigSur. One EFI for all. I install all version. All work and install with no issue. 
Dual boot i use with two ssd. If you have one ssd, you need first create partition for windows and macOS in macOS diskutil, install first windows and last install macOS. OpenCore no need write in config.plist Windows.

**Comment by rajolm** [comment]
@rsdev69 Thank you very much, I moved to OpenCore successfully!
But the intel Wireless didn't work for me at Catalina, do I need to do any thing to make it work?

**Comment by rsdev69** [comment]
> @rsdev69 Thank you very much, I moved to OpenCore successfully!
> But the intel Wireless didn't work for me at Catalina, do I need to do any thing to make it work?

Need to use correct kext for your macOS
https://github.com/OpenIntelWireless/itlwm/releases
![Screenshot 2020-12-02 at 00 11 22](https://user-images.githubusercontent.com/34169770/100802950-f4807300-3432-11eb-8373-bf1bbfd01230.png)
