### ISSUE TITLE
Gray screen after installing Big sur

### ISSUE THREAD

**Issue by rajolm** [rsdev69/ThinkPad-E560-Hackintosh#27]
Hi,
I installed Big sur 11.2 using your last files
When the installation process restarted the laptop, It is now stuck at a gray screen and nothing happen after that
I did a reset for the nvram, now the gray screen flashes quickly then it stuck at the apple logo and loading bar at about 5% and doesn’t move

please help me to fix the issue

**Comment by rsdev69** [comment]
> Hi,
> I installed Big sur 11.2 using your last files
> When the installation process restarted the laptop, It is now stuck at a gray screen and nothing happen after that
> I did a reset for the nvram, now the gray screen flashes quickly then it stuck at the apple logo and loading bar at about 5% and doesn’t move
> 
> please help me to fix the issue

Try to overwrite the installation flash drive, I think you have broken system image. ЕFI folder 100% work. I have already install the system twice and have issue with installation.

**Comment by rajolm** [comment]
> > Hi,
> > I installed Big sur 11.2 using your last files
> > When the installation process restarted the laptop, It is now stuck at a gray screen and nothing happen after that
> > I did a reset for the nvram, now the gray screen flashes quickly then it stuck at the apple logo and loading bar at about 5% and doesn’t move
> > please help me to fix the issue
> 
> Try to overwrite the installation flash drive, I think you have broken system image. ЕFI folder 100% work. I have already install the system twice and have no issue with installation.

Thanks for your response
I really don’t think that the system image is broken 
I was on Catalina and I downloaded the installation app from Apple directly
I ran it directly from Catalina and  *I didn’t flash it on a flash drive*
I will be very grateful if you helped me

**Comment by rsdev69** [comment]
> > > Hi,
> > > I installed Big sur 11.2 using your last files
> > > When the installation process restarted the laptop, It is now stuck at a gray screen and nothing happen after that
> > > I did a reset for the nvram, now the gray screen flashes quickly then it stuck at the apple logo and loading bar at about 5% and doesn’t move
> > > please help me to fix the issue
> > 
> > 
> > Try to overwrite the installation flash drive, I think you have broken system image. ЕFI folder 100% work. I have already install the system twice and have no issue with installation.
> 
> Thanks for your response
> I really don’t think that the system image is broken
> I was on Catalina and I downloaded the installation app from Apple directly
> I ran it directly from Catalina and _I didn’t flash it on a flash drive_
> I will be very grateful if you helped me

You need install only clean install from usb flash. The only way.

**Comment by rajolm** [comment]
> > > > Hi,
> > > > I installed Big sur 11.2 using your last files
> > > > When the installation process restarted the laptop, It is now stuck at a gray screen and nothing happen after that
> > > > I did a reset for the nvram, now the gray screen flashes quickly then it stuck at the apple logo and loading bar at about 5% and doesn’t move
> > > > please help me to fix the issue
> > > 
> > > 
> > > Try to overwrite the installation flash drive, I think you have broken system image. ЕFI folder 100% work. I have already install the system twice and have no issue with installation.
> > 
> > 
> > Thanks for your response
> > I really don’t think that the system image is broken
> > I was on Catalina and I downloaded the installation app from Apple directly
> > I ran it directly from Catalina and _I didn’t flash it on a flash drive_
> > I will be very grateful if you helped me
> 
> You need install only clean install from usb flash. The only way.

But I always upgrade macOS that way, is it something related to big sur?

**Comment by rsdev69** [comment]
> But I always upgrade macOS that way, is it something related to big sur?
Yes, install and update now totally new. Now for all version you need to make new config.plist

**Comment by rajolm** [comment]
> > But I always upgrade macOS that way, is it something related to big sur?
> 
> Yes, install and update now totally new. Now for all version you need to make new config.plist

I can’t access macOS now, I’m on Windows
What you suggest to do to fix this issue 😢

**Comment by rsdev69** [comment]
> > > But I always upgrade macOS that way, is it something related to big sur?
> > 
> > 
> > Yes, install and update now totally new. Now for all version you need to make new config.plist
> 
> I can’t access macOS now, I’m on Windows
> What you suggest to do to fix this issue 😢

Make flash from windows
https://rutracker.org/forum/viewtopic.php?t=5928524

**Comment by rajolm** [comment]
> > But I always upgrade macOS that way, is it something related to big sur?
> 
> Yes, install and update now totally new. Now for all version you need to make new config.plist

I tried the installation from a flash drive but it didn’t work, afternoon the installation process ended it stuck at the grey screen

I used the files from the master branch not the tagged releases
Did you tried it to install 11.2?
I will glad if you helped me figure out how to fix this

**Comment by rsdev69** [comment]
> > > But I always upgrade macOS that way, is it something related to big sur?
> > 
> > 
> > Yes, install and update now totally new. Now for all version you need to make new config.plist
> 
> I tried the installation from a flash drive but it didn’t work, afternoon the installation process ended it stuck at the grey screen
> 
> I used the files from the master branch not the tagged releases
> Did you tried it to install 11.2?
> I will glad if you helped me figure out how to fix this

You need to make a clean installation macOS with full format your hdd or ssd. All data will be lost of course.
