### ISSUE TITLE
Trackpad gestures non working

### ISSUE THREAD

**Issue by gabrielecapp** [rsdev69/ThinkPad-E560-Hackintosh#28]
Hi, are there any chances to make trackpad gestures working?
i've tried adding VoodooInput both in OC and in config.plist but it doesn't work.

**Comment by rsdev69** [comment]
> Hi, are there any chances to make trackpad gestures working?
> i've tried adding VoodooInput both in OC and in config.plist but it doesn't work.

ALPS trackpad not supported by VoodooInput.
Trackpad work only as mouse.
