### ISSUE TITLE
How can i make a SSDT-BATT for my  E570

### ISSUE THREAD

**Issue by relaxewdy** [rsdev69/ThinkPad-E560-Hackintosh#29]
Hi i dont understand how to make SSDT-BATT. I did DSDT patch for my battery and inducator is working but after sleep its just %1. Can you make a guide & tutorial or a video.

**Comment by rsdev69** [comment]
> Hi i dont understand how to make SSDT-BATT. I did DSDT patch for my battery and inducator is working but after sleep its just %1. Can you make a guide & tutorial or a video.

This is repo for Thinkpad battery patch. I make DSDT with this method. 
https://github.com/daliansky/OC-little/tree/master/08-%E7%94%B5%E6%B1%A0%E8%A1%A5%E4%B8%81/08-1-Thinkpad
