### ISSUE TITLE
Installation Halts after 2 mins

### ISSUE THREAD

**Issue by refuzer1** [rsdev69/ThinkPad-E560-Hackintosh#30]
Hi Sergi,
Any cue how can I troubleshoot halting of installation.

**Comment by rsdev69** [comment]
> Hi Sergi,
> Any cue how can I troubleshoot halting of installation.

Add option **-v keepsyms=1**  in boot section config.plist

**Comment by refuzer1** [comment]
Not sure where in boot section. I can see Booter Section, can you post the edited config.plist file

**Comment by rsdev69** [comment]
> Not sure where in boot section. I can see Booter Section, can you post the edited config.plist file

This is last my EFI. Replace and try install.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6371377/EFI.zip)
