### ISSUE TITLE
OC: Driver HfsPlus.efi at 0 cannot be found (OC 0.6.8)

### ISSUE THREAD

**Issue by LeLuyen** [rsdev69/ThinkPad-E560-Hackintosh#31]
![20210425_114016](https://user-images.githubusercontent.com/2620445/115981085-78422400-a5bb-11eb-9400-cd5927d5a878.jpg)

**Comment by LeLuyen** [comment]
https://github.com/rsdev69/ThinkPad-E560-Hackintosh/releases/tag/v2021.04.14

**Comment by rsdev69** [comment]
> https://github.com/rsdev69/ThinkPad-E560-Hackintosh/releases/tag/v2021.04.14

[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6371389/EFI.zip)

**Comment by LeLuyen** [comment]
Hi there,

Thanks you, i will try now

**Comment by LeLuyen** [comment]
Hi Sergi,

It's working now

Thanks you
