### ISSUE TITLE
Problem with similar hardware

### ISSUE THREAD

**Issue by MrPiTA** [rsdev69/ThinkPad-E560-Hackintosh#32]
Hi
I have a lenovo ideapad 510-15ISK laptop with the same processor and graphics. (i3 6100u intel hd520). I installed big sur. Wifi, bluetooth, audio works. I patched the battery so battery status is working, generated kext via CPUFriend to manage cpu.
And I have a problem. My computer works up to a certain point. At some point it is impossible to play movies, e.g. on YouTube and movies that are saved on the local disk.(After my computer is turned on, the movies run for a while. When they stop, I also have a CPU problem - high kernel_task usage)
In VideoProc, it does not detect the HEVC codec. I can see that on your computer the program detects this codec because you have a screenshot attached. The intel power gadget doesn't work for me either. Does it work for you? And the final problem is:
at some point kernel_task uses 100% of my CPU and that causes huge lags and I have to shut down my computer.
I am sending you my EFI folder.
Can you take a peek?
Do you have any idea what I should do?

https://drive.google.com/drive/folders/1wghC6sO4kpYpC1dwP1c6jeAmFYd-fLY-?usp=sharing

![Zrzut ekranu 2021-05-29 o 10 54 50](https://user-images.githubusercontent.com/84288645/120065000-71517a00-c06f-11eb-9edc-d65de8fd33d3.png)

**Comment by rsdev69** [comment]
> Hi
> I have a lenovo ideapad 510-15ISK laptop with the same processor and graphics. (i3 6100u intel hd520).

Hi, try this my config with your configuration.I think it should work fine. Replace EFI folder on my.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6564432/EFI.zip)

**Comment by MrPiTA** [comment]
Now everything seems ok even though VideoProc still doesn't detect the hvec codec. Was your screenshot taken on macos catalina? I read that BigSur forces 10 bit hvec in this case. And our CPU only supports 8 bit hvec and therefore VideoProc doesn't detect this codec. Thank you for your help

**Comment by rsdev69** [comment]
> Now everything seems ok even though VideoProc still doesn't detect the hvec codec. Was your screenshot taken on macos catalina? I read that BigSur forces 10 bit hvec in this case. And our CPU only supports 8 bit hvec and therefore VideoProc doesn't detect this codec. Thank you for your help

In my BigSur VideoProc detect the hvec codec
![4](https://user-images.githubusercontent.com/34169770/120108136-85c76c80-c16c-11eb-97ca-ee08f59b4b5d.png)
