### ISSUE TITLE
how to update to macOs 11.4

### ISSUE THREAD

**Issue by javadmahmoodi670** [rsdev69/ThinkPad-E560-Hackintosh#33]
Hi, I now have Mac 11.0.1 installed on my laptop(E560).  
Now how do I update to version 11.4?
Do I have to re-create a flash boot to install?

**Comment by rsdev69** [comment]
> Hi, I now have Mac 11.0.1 installed on my laptop(E560).
> Now how do I update to version 11.4?
> Do I have to re-create a flash boot to install?

Check updates from control panel and install it.

**Comment by javadmahmoodi670** [comment]
> > Hi, I now have Mac 11.0.1 installed on my laptop(E560).
> 
> > Now how do I update to version 11.4?
> 
> > Do I have to re-create a flash boot to install?
> 
> 
> 
> Check updates from control panel and install it.

After updating the Mac to the new version, and before restarting, should I replace this efi file?  Or should this efi file be replaced before updating?

**Comment by rsdev69** [comment]
> > > Hi, I now have Mac 11.0.1 installed on my laptop(E560).
> > 
> > 
> > > Now how do I update to version 11.4?
> > 
> > 
> > > Do I have to re-create a flash boot to install?
> > 
> > 
> > Check updates from control panel and install it.
> 
> After updating the Mac to the new version, and before restarting, should I replace this efi file? Or should this efi file be replaced before updating?

Always use the latest files from this repo. I update them every month and no problems with updates.
