### ISSUE TITLE
Problem with the latest EFI file

### ISSUE THREAD

**Issue by javadmahmoodi670** [rsdev69/ThinkPad-E560-Hackintosh#34]
Hi, I downloaded and replaced the latest efi file from the source.  But when the Mac comes up, some text is displayed and the Apple logo is not displayed with the line below it as before.
But after finishing the text, the Mac comes up and I just want it to look like the Apple logo and the line below it.
Please help resolve this issue.
my laptop is lenovo E560

![image](https://user-images.githubusercontent.com/77070621/121764348-7119aa00-cb58-11eb-8dea-0227d8cb8e11.jpeg)

**Comment by rsdev69** [comment]
> Hi, I downloaded and replaced the latest efi file from the source. But when the Mac comes up, some text is displayed and the Apple logo is not displayed with the line below it as before.
> But after finishing the text, the Mac comes up and I just want it to look like the Apple logo and the line below it.
> Please help resolve this issue.
> my laptop is lenovo E560

Try clean install from usb flash. I think disk is write-protected and only full formatting will help.

**Comment by javadmahmoodi** [comment]
> > Hi, I downloaded and replaced the latest efi file from the source. But when the Mac comes up, some text is displayed and the Apple logo is not displayed with the line below it as before.
> > But after finishing the text, the Mac comes up and I just want it to look like the Apple logo and the line below it.
> > Please help resolve this issue.
> > my laptop is lenovo E560
> 
> Try clean install from usb flash. I think disk is write-protected and only full formatting will help.

Do you mean to reinstall with Flash Mac?
I will replace the previous efi file again, the problem will be solved.
I think you can fix the problem because I had the same problem before and you gave me a modified version and the problem was fixed

**Comment by rsdev69** [comment]
> Do you mean to reinstall with Flash Mac?
> I will replace the previous efi file again, the problem will be solved.
> I think you can fix the problem because I had the same problem before and you gave me a modified version and the problem was fixed

[ThinkPad-E560-Hackintosh-2021.06.08.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6641886/ThinkPad-E560-Hackintosh-2021.06.08.zip)

**Comment by javadmahmoodi670** [comment]
> > Do you mean to reinstall with Flash Mac?
> 
> > I will replace the previous efi file again, the problem will be solved.
> 
> > I think you can fix the problem because I had the same problem before and you gave me a modified version and the problem was fixed
> 
> 
> 
> [ThinkPad-E560-Hackintosh-2021.06.08.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6641886/ThinkPad-E560-Hackintosh-2021.06.08.zip)
> 
> 
> 
> 

Unfortunately, this file did not resolve the issue.  First the posts appear, then the Apple logo, and finally the Mac login page.  I want no text to be displayed when the Mac comes up, only the Apple logo

**Comment by rsdev69** [comment]
> Unfortunately, this file did not resolve the issue. First the texts appear, then the Apple logo, and finally the Mac login page. I want no text to be displayed when the Mac comes up, only the Apple logo

[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6642139/EFI.zip)

**Comment by robincruseo** [comment]
Hello,

Please I'm encountering issues with boot loop after a the first fresh install and it keeps going on. I have used all the variants of EFI uploaded here.
Kindly find attached the screenshot of the error.
![bootloop error](https://user-images.githubusercontent.com/48361745/125199735-9684fb00-e25f-11eb-80b6-53a0d7f88e93.jpeg)

https://user-images.githubusercontent.com/48361745/125199741-9a188200-e25f-11eb-83d0-73af46db6d18.mp4
