### ISSUE TITLE
Bootloop issues after fresh installation.

### ISSUE THREAD

**Issue by robincruseo** [rsdev69/ThinkPad-E560-Hackintosh#36]
Hello,

![Uploading 
Uploading Bootloop error.mp4…
 error.jpeg…]()
Please I'm encountering issues with boot loop after a the first fresh install and it keeps going on. I have used all the variants of EFI uploaded here.
Kindly find attached the screenshot of the error.

**Comment by rsdev69** [comment]
> Hello,
> 
> 
> Please I'm encountering issues with boot loop after a the first fresh install and it keeps going on. I have used all the variants of EFI uploaded here.
> Kindly find attached the screenshot of the error.

Your screenshot won't open. Make another one.

**Comment by robincruseo** [comment]
Okay,

![bootloop error](https://user-images.githubusercontent.com/48361745/125200777-38a6e200-e264-11eb-8d51-e3ab7db205b5.jpeg)

**Comment by robincruseo** [comment]
I think the OS has installed but during the first restart, it enters into and infinite boot loop all Bios settings are set as displayed in the read me note.

**Comment by rsdev69** [comment]
> My system config is the
> => Lenovo Thinkpad E560 i7 (6th gen pc)
> => 16gb RAM,
> => 2gb AMD graphics.
> 
> I think the OS has installed but during the first restart, it enters into and infinite boot loop all Bios settings are set as displayed in the read me note.
> PS: I could be wrong though

Something is incorrectly set in Bios
![Screenshot 2021-07-11 at 18 27 07](https://user-images.githubusercontent.com/34169770/125201030-1fa72c80-e276-11eb-9ee3-6aee251b86c4.png)
And disable AMD graphics in Bios

**Comment by robincruseo** [comment]
Please kindly help me review the attached screenshots of my current Bios settings/configuration.
Can't seem to find how to disable the AMD graphics in Bios.
[Bios settings.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797230/Bios.settings.zip)

**Comment by rsdev69** [comment]
> Please kindly help me review the attached screenshots of my current Bios settings/configuration.
> Can't seem to find how to disable the AMD graphics in Bios.
> [Bios settings.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797230/Bios.settings.zip)

Everything is set correctly in BIOS
Try clean NVRAM and boot with this EFI
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797294/EFI.zip)

**Comment by robincruseo** [comment]
thanks trying it right away

**Comment by robincruseo** [comment]
Hello,

After clearing the NVRAM and several attempts at loading the OS with the current EFI shared, I run into the error captured in the attachment shared.

Thank you for all your efforts.

[Installer error.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797415/Installer.error.zip)

**Comment by rsdev69** [comment]
> After clearing the NVRAM and several attempts at loading the OS with the current EFI shared, I run into the error captured in the attachment shared.

I disable wifi and bluetooth. Try this EFI.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797489/EFI.zip)

**Comment by robincruseo** [comment]
Hello,

Thank you once again for your prompt response.

I just tried the last EFI twice now and encountered some sort of graphics related error.
See attached.

[Graphics error.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797529/Graphics.error.zip)

**Comment by rsdev69** [comment]
> I just tried the last EFI twice now and encountered some sort of graphics related error.
> See attached.
> [Graphics error.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797529/Graphics.error.zip)

I disable Brightness Keys kext. Try this EFI.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797603/EFI.zip)

**Comment by robincruseo** [comment]
Still getting errors.
[Error.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797659/Error.zip)

**Comment by rsdev69** [comment]
> Still getting errors.
> [Error.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797659/Error.zip)

Try this EFI.

**Comment by robincruseo** [comment]
Hello,

I've been able to get the OS to load and install using the EFI on your repository. However, it did not work for Big Sur 11.4 had to downgrade to 11.2.1 to get it to install.

The PC is fully booted right now.
Brightness is working, 
volume adjustment is working,
Wifi and bluetooth is working,
Mouse trackpad is not working.
keyboard is working fine.

Can you please help me with a fix for the Mouse as I am currently using an external mouse.
Thank you.

Attached is the working EFI from your repo.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797754/EFI.zip)

**Comment by rsdev69** [comment]
> Can you please help me with a fix for the Mouse as I am currently using an external mouse.

Try this.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6799668/EFI.zip)

**Comment by robincruseo** [comment]
Hello,

Thanks for the update.

I tried using the EFI you provided but it was slowing down my PC even at boot mode.
I have managed to get the Mouse trackpad working though not efficiently. 
Encountered another issue where the PC goes to sleep normally but won't start up again without having to restart the force the PC to shut down by holding the Power key and subsequently restarting it.
Also, the brightness keys are not working; unable to adjust brightness though Volume adjustment works just fine.

Please find attached my current working EFI. 
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6802485/EFI.zip)

**Comment by rsdev69** [comment]
> Hello,
> 
> Thanks for the update.
> 
> I tried using the EFI you provided but it was slowing down my PC even at boot mode.
> I have managed to get the Mouse trackpad working though not efficiently.
> Encountered another issue where the PC goes to sleep normally but won't start up again without having to restart the force the PC to shut down by holding the Power key and subsequently restarting it.
> Also, the brightness keys are not working; unable to adjust brightness though Volume adjustment works just fine.

Sleep is not working properly and there is no solution. Don't use sleep.
Brightness keys kext not work, i just disable it.

**Comment by robincruseo** [comment]
Thanks once again for the update.

Much appreciation
