### ISSUE TITLE
Problem installing Mac

### ISSUE THREAD

**Issue by javadmahmoodi670** [rsdev69/ThinkPad-E560-Hackintosh#37]
Hi.  I made the flash boot.  Then I entered the Mac installation phase.  After selecting the partition and installing the Mac, the system reset for the first time.  After this, only the Apple logo is displayed and the system resets very quickly.  I tried several times, but only after displaying the Apple logo, the system resets.  Please help to resolve this issue.  Thank.

**Comment by rsdev69** [comment]
> Hi. I made the flash boot. Then I entered the Mac installation phase. After selecting the partition and installing the Mac, the system reset for the first time. After this, only the Apple logo is displayed and the system resets very quickly. I tried several times, but only after displaying the Apple logo, the system resets. Please help to resolve this issue. Thank.

Currently supported only macOS Monterey 12.0.1 
Any other versions less than Monterey 12.0.1 not work!
This release tested only Monterey 12.0.1 
Catalina, Big Sur installation is not possible.
