### ISSUE TITLE
Big Sur is not installed

### ISSUE THREAD

**Issue by javadmahmoodi670** [rsdev69/ThinkPad-E560-Hackintosh#38]
Hi. I have already installed Mac os Catalina with your help.  
Now I have made a flash boot to install Big Sur and I put my efi folder inside its EFI section, but when installing, only the Apple logo is displayed and Big Sur is not installed.  Please give me the appropriate EFI file to replace.  thank you

**Comment by rsdev69** [comment]
> Hi. I have already installed Mac os Catalina with your help. Now I have made a flash boot to install Big Sur and I put my efi folder inside its EFI section, but when installing, only the Apple logo is displayed and Big Sur is not installed. Please give me the appropriate EFI file to replace. thank you

Hi.
Catalina, Big Sur installation is not possible.
This repo supports only latest macOS Monterey.

**Comment by javadmahmoodi670** [comment]
> > Hi. I have already installed Mac os Catalina with your help. Now I have made a flash boot to install Big Sur and I put my efi folder inside its EFI section, but when installing, only the Apple logo is displayed and Big Sur is not installed. Please give me the appropriate EFI file to replace. thank you
> 
> 
> 
> Hi.
> 
> Catalina, Big Sur installation is not possible.
> 
> This repo supports only latest macOS Monterey.

I create bootable the latest version of the Monterey.  But when I clicked on the installation button, the system reset.  Can you help me how to install the Monterey to solve this problem?

**Comment by rsdev69** [comment]
> I create bootable the latest version of the Monterey. But when I clicked on the installation button, the system reset. Can you help me how to install the Monterey to solve this problem?

Try reset NVRAM, latest EFI from repo.
I tested the installation latest Monterey and I didn’t find any similar problems.

**Comment by javadmahmoodi670** [comment]
> > I create bootable the latest version of the Monterey. But when I clicked on the installation button, the system reset. Can you help me how to install the Monterey to solve this problem?
> 
> 
> 
> Try reset NVRAM, latest EFI from repo.
> 
> I tested the installation latest Monterey and I didn’t find any similar problems.
> 
> 
> 
> 
> 
> 

Hello.  
I did this but I got the following error.  
Please help me to solve my problem

![image](https://user-images.githubusercontent.com/77070621/145769916-a9bf0f8a-c141-433b-a231-86722bfc7dc2.jpeg)

**Comment by rsdev69** [comment]
> Hello. I did this but I got the following error. Please help me to solve my problem

This error often appears when without a key in boot-args **-v keepsyms=1**
Try add this args.

**Comment by javadmahmoodi670** [comment]
> > Hello. I did this but I got the following error. Please help me to solve my problem
> 
> 
> 
> This error often appears when without a key in boot-args **-v keepsyms=1**
> 
> Try add this args.

Where and how do I make these changes?

**Comment by rsdev69** [comment]
> Where and how do I make these changes?
[ThinkPad-E560-Hackintosh-2021.11.25.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/7710978/ThinkPad-E560-Hackintosh-2021.11.25.zip)

**Comment by javadmahmoodi670** [comment]
> > Where and how do I make these changes?
> 
> [ThinkPad-E560-Hackintosh-2021.11.25.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/7710978/ThinkPad-E560-Hackintosh-2021.11.25.zip)
> 
> 
> 
> 

Thanks.  
Put this file in the bootable Flash EFI folder and then install the Mac, or do I have to put it in the current Mac EFI folder before installing the Mac?

**Comment by rsdev69** [comment]
> Thanks. Put this file in the bootable Flash EFI folder and then install the Mac, or do I have to put it in the current Mac EFI folder before installing the Mac?

1. Put this EFI on bootable Flash
2. Full format disk and install macOS
No updates, just a clean install with full disk formatting.

**Comment by javadmahmoodi670** [comment]
> > Thanks. Put this file in the bootable Flash EFI folder and then install the Mac, or do I have to put it in the current Mac EFI folder before installing the Mac?
> 
> 
> 
> 1. Put this EFI on bootable Flash
> 
> 2. Full format disk and install macOS
> 
> No updates, just a clean install with full disk formatting.

I put this file inside the boot Monterey flash.  Then, after restarting the laptop, I clicked on the Monterey installation option.  But after the line under the Apple logo went a little further, the system restarts.  Please help me.  Thanks

**Comment by rsdev69** [comment]
> I put this file inside the boot Monterey flash. Then, after restarting the laptop, I clicked on the Monterey installation option. But after the line under the Apple logo went a little further, the system restarts. Please help me. Thanks

So the image of the system is broken. Download another image.

**Comment by javadmahmoodi670** [comment]
> > I put this file inside the boot Monterey flash. Then, after restarting the laptop, I clicked on the Monterey installation option. But after the line under the Apple logo went a little further, the system restarts. Please help me. Thanks
> 
> So the image of the system is broken. Download another image.

Could you give me the correct image link?

**Comment by rsdev69** [comment]
> Could you give me the correct image link? So that I can download the correct image.

https://apps.apple.com/ua/app/macos-monterey/id1576738294

**Comment by javadmahmoodi670** [comment]
> > Could you give me the correct image link? So that I can download the correct image.
> 
> 
> 
> https://apps.apple.com/ua/app/macos-monterey/id1576738294

Hello.  I downloaded Monterey from Apple Store and made a flash boot.  Then I put the EFI file that you sent in the bootable Flash EFI folder.  And then I installed the Monterey.  But again, after a while the line under the Apple logo moved forward, my laptop restarted.  please guide me.  Thanks

![image](https://user-images.githubusercontent.com/77070621/146634643-d5ca2fb4-a788-4ffc-b312-24404c329415.jpeg)

![image](https://user-images.githubusercontent.com/77070621/146634656-ecb1c2a6-dd42-4409-9d3d-e02ed02b4c69.jpeg)

**Comment by rsdev69** [comment]
> Hello. I downloaded Monterey from Apple Store and made a flash boot. Then I put the EFI file that you sent in the bootable Flash EFI folder. And then I installed the Monterey. But again, after a while the line under the Apple logo moved forward, my laptop restarted. please guide me. Thanks

It can be seen that EFI is working correctly!
The problem is writing to your flash drive.
Take another flash drive and write the image correctly.

**Comment by javadmahmoodi670** [comment]
> > Hello. I downloaded Monterey from Apple Store and made a flash boot. Then I put the EFI file that you sent in the bootable Flash EFI folder. And then I installed the Monterey. But again, after a while the line under the Apple logo moved forward, my laptop restarted. please guide me. Thanks
> 
> 
> 
> It can be seen that EFI is working correctly!
> 
> The problem is writing to your flash drive.
> 
> Take another flash drive and write the image correctly.
> 
> 

Hello.  
Thanks for the good tips.  
I managed to install the Monterey.  But there is only one problem.  When the Monterey rises, instead of seeing the first logo and the line below it, a large number of writings are displayed.  Is it possible to show the Apple logo and the line below it very cleanly?

**Comment by rsdev69** [comment]
> Hello. Thanks for the good tips. I managed to install the Monterey. But there is only one problem. When the Monterey rises, instead of seeing the first logo and the line below it, a large number of writings are displayed. Is it possible to show the Apple logo and the line below it very cleanly?

[Config.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/7740467/Config.zip)
