### ISSUE TITLE
After installing macOS Monterey my ssd does not boot ...

### ISSUE THREAD

**Issue by Lippou** [rsdev69/ThinkPad-E560-Hackintosh#39]
Once I have finished all the installation of macOS Monterey from my usb key to my pc (ssd) I want to boot on my ssd but it does not boot and I stay in the boot menu of the pc ... I really need help please!

**Comment by rsdev69** [comment]
> Once I have finished all the installation of macOS Monterey from my usb key to my pc (ssd) I want to boot on my ssd but it does not boot and I stay in the boot menu of the pc ... I really need help please!

Full format ssd and reinstall macOS Monterey
