### ISSUE TITLE
Kernel not load

### ISSUE THREAD

**Issue by ImAndrew0** [rsdev69/ThinkPad-E560-Hackintosh#40]
Hi, im trying to making an hackintosh on my Thinkpad E560, i have make a USB with the folder containing the macOS recovery files (i have put files into "com.apple.recovery.boot", i have tried macOS Monterey and Big Sur, same problem), but, when i start from USB and select the USB Drive for boot in opencore, it give errors for the kernel loading, and, after 6/9 minutes, its reboot.
I have the model of E560 with the i5, but, i have read on the readme file that EFI is compatible with the E560 family.
I followed the bios settings to set, but the problem persists.

Thanks in advance
Sorry for bad English

**Comment by rsdev69** [comment]
> Hi, im trying to making an hackintosh on my Thinkpad E560, i have make a USB with the folder containing the macOS recovery files (i have put files into "com.apple.recovery.boot", i have tried macOS Monterey and Big Sur, same problem), but, when i start from USB and select the USB Drive for boot in opencore, it give errors for the kernel loading, and, after 6/9 minutes, its reboot. I have the model of E560 with the i5, but, i have read on the readme file that EFI is compatible with the E560 family. I followed the bios settings to set, but the problem persists.

Hi
I think the problem in recovery. 
Don't use recovery. 
Download full image macOS Monterey and correctly install on USB
All recent issues this is are problems with incorrectly created USB.

**Comment by ImAndrew0** [comment]
Hi
I have maked the USB from Windows 11, i have used the macrecovery method.
I have created the 'com.apple.recovery.boot' folder in the usb drive and put in it the downloaded files (BaseSystem.dmg, BaseSystem.chucklist)
After, i downloaded the EFI and put it into the USB Drive.

**Comment by ImAndrew0** [comment]
Thanks, i will try

**Comment by ImAndrew0** [comment]
Hi,
I have maked a USB With full macOS Monterey recovery, but, after the recovery reboot, opencore boot menu disappears, without the possibility of select the device from boot, its starts, but reboot automatically.
