### ISSUE TITLE
OpenCore boot menu disappaers

### ISSUE THREAD

**Issue by ImAndrew0** [rsdev69/ThinkPad-E560-Hackintosh#41]
Hi again,
After install macOS and reboot from recovery, opencore boot menu disappaers.
How can i fix this?

**Comment by rsdev69** [comment]
> Hi again, After install macOS and reboot from recovery, opencore boot menu disappaers. How can i fix this?

Hi
You must always boot from EFI
Install EFI on ssd or boot from your flash drive.

**Comment by ImAndrew0** [comment]
> > Hi again, After install macOS and reboot from recovery, opencore boot menu disappaers. How can i fix this?
> 
> 
> 
> Hi
> 
> You must always boot from EFI
> 
> Install EFI on ssd or boot from your flash drive.

Hi, 
I can't copy the EFI to my ssd for the cause of macOS not boot.
If i boot from the flash drive, it not display the boot menu and select automatically a drive for the boot, but, it reboot automatically

**Comment by rsdev69** [comment]
> Hi, I can't copy the EFI to my ssd for the cause of macOS not boot. If i boot from the flash drive, it not display the boot menu and select automatically a drive for the boot, but, it reboot automatically

So i think you again make wrong installation flash drive. Installation from recovery does not work.
Installation must be complete with full macOS image. 
All reboots, black screens, this is incorrectly write installation flash drive!!!

**Comment by ImAndrew0** [comment]
> > Hi, I can't copy the EFI to my ssd for the cause of macOS not boot. If i boot from the flash drive, it not display the boot menu and select automatically a drive for the boot, but, it reboot automatically
> 
> 
> 
> So i think you again make wrong installation flash drive. Installation from recovery does not work.
> 
> Installation must be complete with full macOS image. 
> 
> All reboots, black screens, this is incorrectly write installation flash drive!!!

I have tried, it reboot

**Comment by rsdev69** [comment]
> I have tried, it reboot

Read old issues 
Here are many such problems solved.
https://github.com/rsdev69/ThinkPad-E560-Hackintosh/issues?q=is%3Aissue+is%3Aclosed
