### ISSUE TITLE
Microphone from 3.5mm Audio Jack not working

### ISSUE THREAD

**Issue by robincruseo** [rsdev69/ThinkPad-E560-Hackintosh#42]
Hello Team,

Much appreciation for all your efforts.

With the previous and current EFI builds, I could never really get the Microphone from a 3.5mm audio jack to work on my machine. Is there a way one could enable this feature?

**Comment by rsdev69** [comment]
> Hello Team,
> 
> Much appreciation for all your efforts.
> 
> With the previous and current EFI builds, I could never really get the Microphone from a 3.5mm audio jack to work on my machine. Is there a way one could enable this feature?

Hi!
On macOS Catalina audio jack work fine.
From Big Sur, Monterey audio jack work 50/50
I do not know how to solve this problem. For the all sound input-output maked AppleALC kext.

**Comment by robincruseo** [comment]
Ok.
Thanks for efforts once again.
