### ISSUE TITLE
Issues with Turning on Bluetooth

### ISSUE THREAD

**Issue by robincruseo** [rsdev69/ThinkPad-E560-Hackintosh#43]
Hello,

Please I'm unable to turn on the Bluetooth using the current EFI. it worked a while back on Big Sur I think; the Wifi also works fine out of the box.
kindly find below the systems Bluetooth information.
![Screen Shot 2022-01-10 at 13 40 39](https://user-images.githubusercontent.com/48361745/148769021-90295132-a204-4c5c-9ffe-e43e94c41e57.png)

**Comment by rsdev69** [comment]
> Hello,
> 
> Please I'm unable to turn on the Bluetooth using the current EFI. it worked a while back on Big Sur I think; the Wifi also works fine out of the box. kindly find below the systems Bluetooth information.

I do not use Intel Bluetooth. 
Bluetooth work terrible.
Intel 3165 has Bluetooth v4.2 and not support OpenIntelWireless.kext
The maximum is a mouse or keyboard connection
https://github.com/OpenIntelWireless

**Comment by robincruseo** [comment]
Thanks for the update.
