### ISSUE TITLE
Can't connect internet with wifi and Ethernet v2022.02.09

### ISSUE THREAD

**Issue by LeLuyen** [rsdev69/ThinkPad-E560-Hackintosh#45]
Hi @rsdev69 

When using EFI of v2022.02.09, there is no internet.

Can you fix?

**Comment by rsdev69** [comment]
> Hi @rsdev69
> 
> When using EFI of v2022.02.09, there is no internet.
> 
> Can you fix?

Try other release, no way to check now this issue.
