### ISSUE TITLE
Install mac os on asus n7600pc

### ISSUE THREAD

**Issue by javadmahmoodi670** [rsdev69/ThinkPad-E560-Hackintosh#46]
Hello.  
I recently changed my Lenovo laptop and bought a new Asus n7600pc laptop.  
Can I run and install the same efi folder Mac file on my new laptop?  please guide me.  Thanks

**Comment by rsdev69** [comment]
> Hello. I recently changed my Lenovo laptop and bought a new Asus n7600pc laptop. Can I run and install the same efi folder Mac file on my new laptop? please guide me. Thanks

No, this is imposible.

**Comment by javadmahmoodi670** [comment]
Thank you
