### ISSUE TITLE
Cant install MacOS

### ISSUE THREAD

**Issue by KenDxD** [rsdev69/ThinkPad-E560-Hackintosh#47]
I tried to flash niresh catalina and use your efi but I cant boot to macOS installation just on bootloader. Can you recommend me a file that you use to boot up macOS?

**Comment by rsdev69** [comment]
> I tried to flash niresh catalina and use your efi but I cant boot to macOS installation just on bootloader. Can you recommend me a file that you use to boot up macOS?

With this repo you can insatall only Big Sur or Monterey. 
For install Catalina need to reconfigure OpenCore with **SecureBootModel** in **disabled** and kexts for Catalina.

**Comment by KenDxD** [comment]
Does dortanias guide for Big Sur will work if I use this Efi? com.apple.recovery.boot that method?

**Comment by rsdev69** [comment]
> Does dortanias guide for Big Sur will work if I use this Efi? com.apple.recovery.boot that method?

Recovery works.

**Comment by KenDxD** [comment]
![IMG20220701124623](https://user-images.githubusercontent.com/41190270/176825213-90ea2c7d-d031-481a-b9e5-fc06ca93a331.jpg)
Got this issue

**Comment by rsdev69** [comment]
> Got this issue

This is not issue. 
Write correct installation files.

**Comment by KenDxD** [comment]
I already followed dortanias guide, put the recovery to com.apple.recovery.boot and your efi

**Comment by KenDxD** [comment]
It boot up, I just to wait for 4 mins then after that error.

**Comment by KenDxD** [comment]
Final, how to change the language to english? I modify the config to set to english but no luck

**Comment by rsdev69** [comment]
> Final, how to change the language to english? I modify the config to set to english but no luck

Delete this in config
<key>prev-lang:kbd</key>
<data>cnUtUlU6MjUy</data>

**Comment by KenDxD** [comment]
How much time it needed to install?
![Uploading IMG20220701153513.jpg…]()

**Comment by rsdev69** [comment]
~1 hour
