### ISSUE TITLE
Bluetooth fix

### ISSUE THREAD

**Issue by KenDxD** [rsdev69/ThinkPad-E560-Hackintosh#50]
So the recent version you release, the bluetooth wont turn on and I manage to fix by finding some reference on reddit and olarila
[Bluetooth fix v1.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/9033257/Bluetooth.fix.v1.zip)

**Comment by KenDxD** [comment]
working on Monterey

**Comment by rsdev69** [comment]
> So the recent version you release, the bluetooth wont turn on and I manage to fix by finding some reference on reddit and olarila [Bluetooth fix v1.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/9033257/Bluetooth.fix.v1.zip)

If use intel 3165 module, easier replace it. This is terrible card.

**Comment by KenDxD** [comment]
can you recommend me a better upgrade for wifi? The issue of this card is I cant put the laptop on sleep because ifit turn on the wifi wont work need to reboot the OS.

**Comment by rsdev69** [comment]
> can you recommend me a better upgrade for wifi? The issue of this card is I cant put the laptop on sleep because ifit turn on the wifi wont work need to reboot the OS.

Sleep not working correct here, any other card not help you.
