### ISSUE TITLE
SSDT-PLUG is not enabled by default

### ISSUE THREAD

**Issue by KenDxD** [rsdev69/ThinkPad-E560-Hackintosh#55]
I would like to tell people here that the SSDT-PLUG is not enabled by default so please configure it on the config.plist. I notice it by using OpenCore Configurator>Config Checker via "Tools"

**Comment by rsdev69** [comment]
> I would like to tell people here that the SSDT-PLUG is not enabled by default so please configure it on the config.plist. I notice it by using OpenCore Configurator>Config Checker via "Tools"

Do not use  OpenCore Configurator.
