### ISSUE TITLE
Ran some tests, one issue

### ISSUE THREAD

**Issue by 1tech23** [rsdev69/ThinkPad-E560-Hackintosh#58]
I was able to get Catalina up and running with the kexts for Monterey. However, I had an issue with connecting to a wireless network. The Bluetooth worked fine, because of the fix that was provided in a previous post on this area. My ThinkPad is the i5-6210u model, has 16gb DDR3L at 1600 MHz. MacOS is installed on a slow 750gb 2.5in HDD at 1500 rpm. I am checking to see if upgrading to Monterey from Mac is working.

In case you want to know, I used a tool called GibMacOS to create the installer then copied all of the kexts and whatnot over from this repository to the EFI partition of the drive in their respective locations. For whatever reason, GibMacOS wasn't downloading the right packages for Monterey or Ventura, so I went with Catalina and it worked fine. GibMacOS downloads the .pkg files for the InstallAssistant directly from Apple itself and it builds the majority of the OpenCore EFI partition automatically, though some tweaking is still required by the user (specifically when it comes to the config.plist file)

Here is a link to GibMacOS: https://github.com/corpnewt/gibMacOS

You can run it anywhere, but it depends on the Python3 package. It can be run from Linux, Windows, or Mac, so long as you have Python3 installed

Just thought this was useful information for anybody interested

**Comment by rsdev69** [comment]
> Just thought this was useful information for anybody interested

This laptop can run any version from El Capitan to Ventura. OpenCore run all version.

**Comment by oneenterprisestech** [comment]
> > Just thought this was useful information for anybody interested
> 
> This laptop can run any version from El Capitan to Ventura. OpenCore run all version.

Presumably, but it seems that issues may arise like I stated, for example, with connectivity and wireless networks
