### ISSUE TITLE
HDMI isn't working for i5-6200U model on MacOS Ventura

### ISSUE THREAD

**Issue by JOEJOEO** [rsdev69/ThinkPad-E560-Hackintosh#59]
Hi there, first ı gotta say thank you for saving us lots of time with this great job. I've been using your efi file with opencore configurator for around a month now and only issues ı came up with is the hdmı and bluetooth not working. As far as ı know my bluetooth is not working because these intel ones aren't  working properly on Ventura but that's ok ım cool with it. But ı really do need HDMI to be working properly. I was wondering can you help me out about this?(Device using intel 520 graphic card)

**Comment by rsdev69** [comment]
> I was wondering can you help me out about this?(Device using intel 520 graphic card)

Hi! I don't use a long time this notebook. All I can do is update latest Opencore with kexts. I updated repo and for Ventura applied patches for graphic from macOS Monterey. Hope they work.

**Comment by JOEJOEO** [comment]
Thank you for your attention. I'll try them now ı really hope they'll work 🙏🏼
